{
    "catchAll": {
        "phrases": [
            "Извините я вас не понял , попробуйте сначала , для этого нужно сказать \"привет\""
        ]
    },
    "fulfillment": {
        "settings": {
            "default": {
                "url": ""
            },
            "channels": []
        },
        "actions": []
    }
}