{
    "catchAll": {
        "phrases": [
            "Извините, непонятно"
        ]
    },
    "fulfillment": {
        "settings": {
            "default": {
                "url": "https://hh.aimylogic.com/webhook/int8dz0j"
            },
            "channels": [
                {
                    "channelId": "81737966-letu1_hr_new-81737966-XuG-158175600",
                    "url": "https://hh.aimylogic.com/webhook/int8dz0j"
                },
                {
                    "channelId": "81737966-letu1_hr_new-81737966-XuG-158175601",
                    "url": "https://hh.aimylogic.com/webhook/int8dz0j"
                }
            ]
        },
        "actions": [
            {
                "state": "/newNode_28",
                "action": "save_age_score",
                "enabled": true
            },
            {
                "state": "/newNode_0",
                "action": "start",
                "enabled": true,
                "color": "#1ccad8"
            },
            {
                "state": "/newNode_63",
                "action": "save_city_score",
                "enabled": true
            },
            {
                "state": "/newNode_73",
                "action": "name",
                "enabled": true,
                "color": ""
            },
            {
                "state": "/newNode_22",
                "action": "save_citizenship",
                "enabled": true
            },
            {
                "state": "/newNode_60",
                "action": "data",
                "enabled": true
            },
            {
                "state": "/newNode_93",
                "action": "save_data",
                "enabled": false
            },
            {
                "state": "/newNode_32",
                "action": "save_employment_score",
                "enabled": true
            },
            {
                "state": "/newNode_64",
                "action": "save_schedule",
                "enabled": true
            },
            {
                "state": "/newNode_37",
                "action": "save_education_score",
                "enabled": true
            },
            {
                "state": "/newNode_38",
                "action": "save_education_score",
                "enabled": true
            },
            {
                "state": "/newNode_41",
                "action": "save_education_score",
                "enabled": true
            },
            {
                "state": "/newNode_66",
                "action": "save_education_schedule",
                "enabled": true
            },
            {
                "state": "/newNode_127",
                "action": "save_student_score",
                "enabled": true
            },
            {
                "state": "/newNode_35",
                "action": "save_schedule_score",
                "enabled": true
            },
            {
                "state": "/newNode_95",
                "action": "phone",
                "enabled": true,
                "color": ""
            },
            {
                "state": "/newNode_118",
                "action": "date",
                "enabled": true
            },
            {
                "state": "/newNode_160",
                "action": "save_employment_score",
                "enabled": true
            },
            {
                "state": "/newNode_176",
                "action": "save_particular_schedule",
                "enabled": true
            },
            {
                "state": "/newNode_150",
                "action": "save_location_score",
                "enabled": true
            },
            {
                "state": "/newNode_101",
                "action": "save_student_score",
                "enabled": true
            },
            {
                "state": "/newNode_153",
                "action": "save_employment_period_score",
                "enabled": true
            },
            {
                "state": "/newNode_156",
                "action": "save_mobile",
                "enabled": true
            },
            {
                "state": "/newNode_133",
                "action": "ready",
                "enabled": true,
                "color": "#edc9ff"
            },
            {
                "state": "/newNode_131",
                "action": "sex",
                "enabled": true,
                "color": "#edc9ff"
            },
            {
                "state": "/newNode_140",
                "action": "city",
                "color": "#edc9ff",
                "enabled": true
            },
            {
                "state": "/newNode_146",
                "action": "citizenship",
                "color": "#edc9ff",
                "enabled": true
            },
            {
                "state": "/newNode_99",
                "action": "age",
                "enabled": true,
                "color": "#edc9ff"
            },
            {
                "state": "/newNode_134",
                "action": "failed",
                "enabled": true
            },
            {
                "state": "/newNode_120",
                "action": "success",
                "enabled": true,
                "color": ""
            },
            {
                "state": "/newNode_67",
                "action": "time",
                "enabled": true
            },
            {
                "state": "/newNode_74",
                "action": "job_interview",
                "color": "",
                "enabled": true
            }
        ]
    },
    "tariffLimit": {
        "phrases": [
            "Извините, работа временно приостановлена"
        ]
    }
}